stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - >-
      curl 
      -H "Content-Type: application/json" 
      -X POST
      --data "
      {
      \"unique_name\": \"$GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG\"
      }
      "
      "https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@api.gigalixir.com/api/apps" 
    - git remote add gigalixir "https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG.git"
    - git push gigalixir HEAD:refs/heads/master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG.gigalixirapp.com
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://bar-staging.gigalixirapp.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://bar.gigalixirapp.com
  when: manual
  only:
  - master

