image: ubuntu:16.04

stages:
  - deploy

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
    - apt-get update
    - apt-get install -y python-pip
    - pip install gigalixir
    - echo "Creating gigalixir app $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG"
    - gigalixir create --name $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG
    - echo "Pushing"
    - git push -f gigalixir HEAD:refs/heads/master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG.gigalixirapp.com
    on_stop: stop_review
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - echo "Adding git remote"
    - git remote add gigalixir "https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME-staging.git"
    - echo "Pushing to gigalixir"
    - git push gigalixir HEAD:refs/heads/master
  environment:
    name: staging
    url: https://$GIGALIXIR_APP_NAME-staging.gigalixirapp.com
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - echo "Adding git remote"
    - git remote add gigalixir "https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git"
    - echo "Pushing to gigalixir"
    - git push gigalixir HEAD:refs/heads/master
  environment:
    name: production
    url: https://$GIGALIXIR_APP_NAME.gigalixirapp.com
  when: manual
  only:
  - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - apt-get update
    - apt-get install -y python-pip
    - pip install gigalixir
    - echo "Scaling app $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG to 0 replicas"
    - gigalixir scale --replicas=0 $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG
    - echo "Deleting app $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG"
    - gigalixir delete_app $GIGALIXIR_APP_NAME-$CI_ENVIRONMENT_SLUG
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master

